# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NoteTaking Dev Tran Nhat Sang - Personal
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal knowledge base and note-taking website. A collection of thoughts,
  learnings, and insights organized for easy reference and sharing.
baseurl: "/note-taking" # the subpath of your site, e.g. /blog
url: "https://sangtrandev00.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: sangtrandev00

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

# Just the Docs theme settings
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true

# Navigation structure
nav_external_links:
  - title: GitHub
    url: https://github.com
    hide_icon: false

# Footer content
footer_content: "Copyright &copy; 2025 NoteTaking. Distributed by an <a href=\"https://github.com\">Open Source</a> license."

# Color scheme can be: light, dark, auto
color_scheme: light

# Google Analytics (optional)
# ga_tracking: UA-XXXXXXXX-X

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ../obsidian-vault/
  - ../shared/
  - .DS_Store
  - "*.pdf"

# Show future posts
future: true
